/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZazitkyRouteImport } from './routes/zazitky'
import { Route as ZasadyOchranyOsobnichUdajuRouteImport } from './routes/zasady-ochrany-osobnich-udaju'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZazitkySlugRouteImport } from './routes/zazitky.$slug'

const ZazitkyRoute = ZazitkyRouteImport.update({
  id: '/zazitky',
  path: '/zazitky',
  getParentRoute: () => rootRouteImport,
} as any)
const ZasadyOchranyOsobnichUdajuRoute =
  ZasadyOchranyOsobnichUdajuRouteImport.update({
    id: '/zasady-ochrany-osobnich-udaju',
    path: '/zasady-ochrany-osobnich-udaju',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZazitkySlugRoute = ZazitkySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ZazitkyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/playlist': typeof PlaylistRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
  '/zazitky': typeof ZazitkyRouteWithChildren
  '/zazitky/$slug': typeof ZazitkySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/playlist': typeof PlaylistRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
  '/zazitky': typeof ZazitkyRouteWithChildren
  '/zazitky/$slug': typeof ZazitkySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/playlist': typeof PlaylistRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
  '/zazitky': typeof ZazitkyRouteWithChildren
  '/zazitky/$slug': typeof ZazitkySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/playlist'
    | '/zasady-ochrany-osobnich-udaju'
    | '/zazitky'
    | '/zazitky/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/playlist'
    | '/zasady-ochrany-osobnich-udaju'
    | '/zazitky'
    | '/zazitky/$slug'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/o-mne'
    | '/obchodni-podminky'
    | '/playlist'
    | '/zasady-ochrany-osobnich-udaju'
    | '/zazitky'
    | '/zazitky/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OMneRoute: typeof OMneRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  PlaylistRoute: typeof PlaylistRoute
  ZasadyOchranyOsobnichUdajuRoute: typeof ZasadyOchranyOsobnichUdajuRoute
  ZazitkyRoute: typeof ZazitkyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zazitky': {
      id: '/zazitky'
      path: '/zazitky'
      fullPath: '/zazitky'
      preLoaderRoute: typeof ZazitkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zasady-ochrany-osobnich-udaju': {
      id: '/zasady-ochrany-osobnich-udaju'
      path: '/zasady-ochrany-osobnich-udaju'
      fullPath: '/zasady-ochrany-osobnich-udaju'
      preLoaderRoute: typeof ZasadyOchranyOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zazitky/$slug': {
      id: '/zazitky/$slug'
      path: '/$slug'
      fullPath: '/zazitky/$slug'
      preLoaderRoute: typeof ZazitkySlugRouteImport
      parentRoute: typeof ZazitkyRoute
    }
  }
}

interface ZazitkyRouteChildren {
  ZazitkySlugRoute: typeof ZazitkySlugRoute
}

const ZazitkyRouteChildren: ZazitkyRouteChildren = {
  ZazitkySlugRoute: ZazitkySlugRoute,
}

const ZazitkyRouteWithChildren =
  ZazitkyRoute._addFileChildren(ZazitkyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OMneRoute: OMneRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  PlaylistRoute: PlaylistRoute,
  ZasadyOchranyOsobnichUdajuRoute: ZasadyOchranyOsobnichUdajuRoute,
  ZazitkyRoute: ZazitkyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
